services:
  api-backend:
    build: ./backend
    container_name: mi_backend_autosys
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  web-frontend:
    build:
      context: ./frontend
      # 👇 Pasamos la variable a la fase de construcción de Next.js 👇
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: mi_frontend_autosys
    restart: always
    ports:
      - "3005:3000"
    depends_on:
      - api-backend
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
