import { PrismaClient } from '../../../generated/prisma/client.js'

const now = () => new Date()
const startOfCurrentMonth = () => {
  const d = new Date()
  return new Date(d.getFullYear(), d.getMonth(), 1)
}

export async function getCrmDashboard(db: unknown, empresaId: string) {
  const prisma = db as PrismaClient
  const monthStart = startOfCurrentMonth()
  const currentNow = now()

  const [
    leadsTotal,
    leadsThisMonth,
    leadsByStatusNew,
    leadsByStatusContacted,
    leadsByStatusQualified,
    leadsByStatusProposal,
    leadsByStatusNegotiation,
    leadsByStatusWon,
    leadsByStatusLost,
    leadsByChannelRepuestos,
    leadsByChannelTaller,
    leadsByChannelVehiculos,
    leadsWonThisMonth,
    leadsLostThisMonth,
    recentLeads,

    quotesTotal,
    quotesActive,
    quotesByStatusDraft,
    quotesByStatusIssued,
    quotesByStatusSent,
    quotesByStatusNegotiating,
    quotesByStatusApproved,
    quotesByStatusRejected,
    quotesByStatusExpired,
    quotesByStatusConverted,
    quotesApprovedThisMonth,
    activeQuotesForPipeline,
    recentQuotes,

    casesTotal,
    casesOpen,
    casesOverdue,
    casesByPriorityLow,
    casesByPriorityMedium,
    casesByPriorityHigh,
    casesByPriorityCritical,
    casesByStatusOpen,
    casesByStatusInAnalysis,
    casesByStatusInProgress,
    casesByStatusWaitingClient,
    casesByStatusEscalated,
    casesByStatusResolved,
    casesByStatusClosed,
    casesByStatusRejected,
    casesResolvedThisMonth,
    recentCases,

    customersTotal,
    customersActive,
    customersNewThisMonth,
    customersBySegmentProspect,
    customersBySegmentRegular,
    customersBySegmentVip,
    customersBySegmentWholesale,
    customersBySegmentInactive,

    activitiesPending,
    activitiesOverdue,
    activitiesCompletedThisMonth,
    recentOverdueActivities,

    serviceOrdersActive,
    serviceOrdersDeliveredThisMonth,
    deliveredSOsThisMonth,

    opportunitiesTotal,
    opportunitiesOpen,
    opportunitiesWonThisMonth,
    opportunitiesLostThisMonth,
    opportunitiesByChannelRepuestos,
    opportunitiesByChannelTaller,
    opportunitiesByChannelVehiculos,
    opportunitiesOverdueActivities,
    opportunitiesPipelineRows,
    opportunitiesRecent,
    opportunitiesStale,

    alertsOpen,
    recentAlerts,
  ] = await Promise.all([
    prisma.lead.count({ where: { empresaId } }),
    prisma.lead.count({ where: { empresaId, createdAt: { gte: monthStart } } }),
    prisma.lead.count({ where: { empresaId, status: 'NEW' } }),
    prisma.lead.count({ where: { empresaId, status: 'CONTACTED' } }),
    prisma.lead.count({ where: { empresaId, status: 'QUALIFIED' } }),
    prisma.lead.count({ where: { empresaId, status: 'PROPOSAL' } }),
    prisma.lead.count({ where: { empresaId, status: 'NEGOTIATION' } }),
    prisma.lead.count({ where: { empresaId, status: 'WON' } }),
    prisma.lead.count({ where: { empresaId, status: 'LOST' } }),
    prisma.lead.count({ where: { empresaId, channel: 'REPUESTOS' } }),
    prisma.lead.count({ where: { empresaId, channel: 'TALLER' } }),
    prisma.lead.count({ where: { empresaId, channel: 'VEHICULOS' } }),
    prisma.lead.count({ where: { empresaId, status: 'WON', closedAt: { gte: monthStart } } }),
    prisma.lead.count({ where: { empresaId, status: 'LOST', closedAt: { gte: monthStart } } }),
    prisma.lead.findMany({
      where: { empresaId },
      orderBy: { createdAt: 'desc' },
      take: 5,
      select: { id: true, title: true, channel: true, status: true, customer: { select: { name: true } }, createdAt: true },
    }),

    prisma.quote.count({ where: { empresaId } }),
    prisma.quote.count({ where: { empresaId, status: { notIn: ['REJECTED', 'EXPIRED', 'CONVERTED'] as any } } }),
    prisma.quote.count({ where: { empresaId, status: 'DRAFT' } }),
    prisma.quote.count({ where: { empresaId, status: 'ISSUED' } }),
    prisma.quote.count({ where: { empresaId, status: 'SENT' } }),
    prisma.quote.count({ where: { empresaId, status: 'NEGOTIATING' } }),
    prisma.quote.count({ where: { empresaId, status: 'APPROVED' } }),
    prisma.quote.count({ where: { empresaId, status: 'REJECTED' } }),
    prisma.quote.count({ where: { empresaId, status: 'EXPIRED' } }),
    prisma.quote.count({ where: { empresaId, status: 'CONVERTED' } }),
    prisma.quote.count({ where: { empresaId, status: 'APPROVED', createdAt: { gte: monthStart } } }),
    prisma.quote.findMany({ where: { empresaId, status: { notIn: ['REJECTED', 'EXPIRED', 'CONVERTED'] as any } }, select: { total: true } }),
    prisma.quote.findMany({
      where: { empresaId },
      orderBy: { createdAt: 'desc' },
      take: 5,
      select: { id: true, quoteNumber: true, title: true, status: true, total: true, customer: { select: { name: true } }, createdAt: true },
    }),

    prisma.case.count({ where: { empresaId } }),
    prisma.case.count({ where: { empresaId, status: { notIn: ['CLOSED', 'REJECTED'] as any } } }),
    prisma.case.count({ where: { empresaId, slaDeadline: { lt: currentNow }, status: { notIn: ['RESOLVED', 'CLOSED', 'REJECTED'] as any } } }),
    prisma.case.count({ where: { empresaId, priority: 'LOW' } }),
    prisma.case.count({ where: { empresaId, priority: 'MEDIUM' } }),
    prisma.case.count({ where: { empresaId, priority: 'HIGH' } }),
    prisma.case.count({ where: { empresaId, priority: 'CRITICAL' } }),
    prisma.case.count({ where: { empresaId, status: 'OPEN' } }),
    prisma.case.count({ where: { empresaId, status: 'IN_ANALYSIS' } }),
    prisma.case.count({ where: { empresaId, status: 'IN_PROGRESS' } }),
    prisma.case.count({ where: { empresaId, status: 'WAITING_CLIENT' } }),
    prisma.case.count({ where: { empresaId, status: 'ESCALATED' } }),
    prisma.case.count({ where: { empresaId, status: 'RESOLVED' } }),
    prisma.case.count({ where: { empresaId, status: 'CLOSED' } }),
    prisma.case.count({ where: { empresaId, status: 'REJECTED' } }),
    prisma.case.count({ where: { empresaId, status: 'RESOLVED', resolvedAt: { gte: monthStart } } }),
    prisma.case.findMany({
      where: { empresaId },
      orderBy: { createdAt: 'desc' },
      take: 5,
      select: { id: true, caseNumber: true, title: true, priority: true, status: true, slaDeadline: true, customer: { select: { name: true } }, createdAt: true },
    }),

    prisma.customer.count({ where: { empresaId } }),
    prisma.customer.count({ where: { empresaId, isActive: true } }),
    prisma.customer.count({ where: { empresaId, createdAt: { gte: monthStart } } }),
    prisma.customer.count({ where: { empresaId, segment: 'PROSPECT' } }),
    prisma.customer.count({ where: { empresaId, segment: 'REGULAR' } }),
    prisma.customer.count({ where: { empresaId, segment: 'VIP' } }),
    prisma.customer.count({ where: { empresaId, segment: 'WHOLESALE' } }),
    prisma.customer.count({ where: { empresaId, segment: 'INACTIVE' } }),

    prisma.activity.count({ where: { empresaId, status: 'PENDING' } }),
    prisma.activity.count({ where: { empresaId, status: 'PENDING', dueAt: { lt: currentNow } } }),
    prisma.activity.count({ where: { empresaId, status: 'DONE', completedAt: { gte: monthStart } } }),
    prisma.activity.findMany({
      where: { empresaId, status: 'PENDING', dueAt: { lt: currentNow } },
      orderBy: { dueAt: 'asc' },
      take: 5,
      select: { id: true, title: true, type: true, dueAt: true, assignedTo: true },
    }),

    prisma.serviceOrder.count({ where: { empresaId, status: { notIn: ['DELIVERED', 'CANCELLED'] as any } } }),
    prisma.serviceOrder.count({ where: { empresaId, status: 'DELIVERED', deliveredAt: { gte: monthStart } } }),
    prisma.serviceOrder.findMany({ where: { empresaId, status: 'DELIVERED', deliveredAt: { gte: monthStart } }, select: { total: true } }),

    prisma.opportunity.count({ where: { empresaId } }),
    prisma.opportunity.count({ where: { empresaId, status: 'OPEN' } }),
    prisma.opportunity.count({ where: { empresaId, status: 'WON', wonAt: { gte: monthStart } } }),
    prisma.opportunity.count({ where: { empresaId, status: 'LOST', lostAt: { gte: monthStart } } }),
    prisma.opportunity.count({ where: { empresaId, channel: 'REPUESTOS' } }),
    prisma.opportunity.count({ where: { empresaId, channel: 'TALLER' } }),
    prisma.opportunity.count({ where: { empresaId, channel: 'VEHICULOS' } }),
    prisma.opportunity.count({ where: { empresaId, status: 'OPEN', nextActivityAt: { lt: currentNow } } }),
    prisma.opportunity.findMany({ where: { empresaId, status: 'OPEN' }, select: { amount: true } }),
    prisma.opportunity.findMany({
      where: { empresaId },
      orderBy: { createdAt: 'desc' },
      take: 5,
      select: {
        id: true,
        title: true,
        channel: true,
        stageCode: true,
        status: true,
        amount: true,
        ownerId: true,
        nextActivityAt: true,
        expectedCloseAt: true,
        createdAt: true,
      },
    }),
    prisma.opportunity.count({ where: { empresaId, status: 'OPEN', updatedAt: { lt: new Date(currentNow.getTime() - 7 * 24 * 60 * 60 * 1000) } } }),

    prisma.crmAutomationAlert.count({ where: { empresaId, status: 'OPEN' } }),
    prisma.crmAutomationAlert.findMany({
      where: { empresaId, status: 'OPEN' },
      orderBy: { createdAt: 'desc' },
      take: 5,
      select: { id: true, type: true, severity: true, title: true, message: true, createdAt: true, entityType: true, entityId: true },
    }),
  ])

  const wonPlusLost = leadsWonThisMonth + leadsLostThisMonth
  const conversionRate = wonPlusLost > 0 ? (leadsWonThisMonth / wonPlusLost) * 100 : 0

  const pipelineValue = activeQuotesForPipeline.reduce((acc, q) => acc + Number(q.total), 0)
  const totalRevenueThisMonth = deliveredSOsThisMonth.reduce((acc, so) => acc + Number(so.total), 0)

  const oppWonPlusLost = opportunitiesWonThisMonth + opportunitiesLostThisMonth
  const oppWinRate = oppWonPlusLost > 0 ? (opportunitiesWonThisMonth / oppWonPlusLost) * 100 : 0
  const opportunitiesPipelineValue = opportunitiesPipelineRows.reduce((acc, row) => acc + Number(row.amount ?? 0), 0)

  return {
    leads: {
      total: leadsTotal,
      thisMonth: leadsThisMonth,
      byStatus: {
        NEW: leadsByStatusNew,
        CONTACTED: leadsByStatusContacted,
        QUALIFIED: leadsByStatusQualified,
        PROPOSAL: leadsByStatusProposal,
        NEGOTIATION: leadsByStatusNegotiation,
        WON: leadsByStatusWon,
        LOST: leadsByStatusLost,
      } as Record<string, number>,
      byChannel: {
        REPUESTOS: leadsByChannelRepuestos,
        TALLER: leadsByChannelTaller,
        VEHICULOS: leadsByChannelVehiculos,
      } as Record<string, number>,
      wonThisMonth: leadsWonThisMonth,
      lostThisMonth: leadsLostThisMonth,
      conversionRate: Math.round(conversionRate * 100) / 100,
      recentLeads,
    },
    opportunities: {
      total: opportunitiesTotal,
      open: opportunitiesOpen,
      wonThisMonth: opportunitiesWonThisMonth,
      lostThisMonth: opportunitiesLostThisMonth,
      winRate: Math.round(oppWinRate * 100) / 100,
      pipelineValue: opportunitiesPipelineValue,
      stale: opportunitiesStale,
      overdueActivities: opportunitiesOverdueActivities,
      byChannel: {
        REPUESTOS: opportunitiesByChannelRepuestos,
        TALLER: opportunitiesByChannelTaller,
        VEHICULOS: opportunitiesByChannelVehiculos,
      } as Record<string, number>,
      recent: opportunitiesRecent.map((row) => ({ ...row, amount: Number(row.amount ?? 0) })),
    },
    quotes: {
      total: quotesTotal,
      active: quotesActive,
      pipelineValue,
      byStatus: {
        DRAFT: quotesByStatusDraft,
        ISSUED: quotesByStatusIssued,
        SENT: quotesByStatusSent,
        NEGOTIATING: quotesByStatusNegotiating,
        APPROVED: quotesByStatusApproved,
        REJECTED: quotesByStatusRejected,
        EXPIRED: quotesByStatusExpired,
        CONVERTED: quotesByStatusConverted,
      } as Record<string, number>,
      approvedThisMonth: quotesApprovedThisMonth,
      recentQuotes: recentQuotes.map((q) => ({ ...q, total: Number(q.total) })),
    },
    cases: {
      total: casesTotal,
      open: casesOpen,
      overdue: casesOverdue,
      byPriority: {
        LOW: casesByPriorityLow,
        MEDIUM: casesByPriorityMedium,
        HIGH: casesByPriorityHigh,
        CRITICAL: casesByPriorityCritical,
      } as Record<string, number>,
      byStatus: {
        OPEN: casesByStatusOpen,
        IN_ANALYSIS: casesByStatusInAnalysis,
        IN_PROGRESS: casesByStatusInProgress,
        WAITING_CLIENT: casesByStatusWaitingClient,
        ESCALATED: casesByStatusEscalated,
        RESOLVED: casesByStatusResolved,
        CLOSED: casesByStatusClosed,
        REJECTED: casesByStatusRejected,
      } as Record<string, number>,
      resolvedThisMonth: casesResolvedThisMonth,
      recentCases,
    },
    customers: {
      total: customersTotal,
      active: customersActive,
      newThisMonth: customersNewThisMonth,
      bySegment: {
        PROSPECT: customersBySegmentProspect,
        REGULAR: customersBySegmentRegular,
        VIP: customersBySegmentVip,
        WHOLESALE: customersBySegmentWholesale,
        INACTIVE: customersBySegmentInactive,
      } as Record<string, number>,
    },
    activities: {
      pending: activitiesPending,
      overdue: activitiesOverdue,
      completedThisMonth: activitiesCompletedThisMonth,
      recentOverdue: recentOverdueActivities,
    },
    alerts: {
      open: alertsOpen,
      recent: recentAlerts,
    },
    serviceOrders: {
      active: serviceOrdersActive,
      deliveredThisMonth: serviceOrdersDeliveredThisMonth,
      totalRevenueThisMonth,
    },
  }
}
