import { PERMISSIONS } from './permissions.js'

const P = PERMISSIONS

const uniquePermissions = (
  ...groups: ReadonlyArray<ReadonlyArray<string>>
): string[] => Array.from(new Set(groups.flat()))

const ALL_USERS = [
  P.USERS_VIEW,
  P.USERS_CREATE,
  P.USERS_UPDATE,
  P.USERS_DELETE,
  P.USERS_APPROVE,
] as const

const ALL_PLATFORM_USERS = [
  P.PLATFORM_USERS_VIEW,
  P.PLATFORM_USERS_CREATE,
  P.PLATFORM_USERS_UPDATE,
  P.PLATFORM_USERS_DELETE,
] as const

const ALL_COMPANIES = [
  P.COMPANIES_VIEW,
  P.COMPANIES_CREATE,
  P.COMPANIES_UPDATE,
  P.COMPANIES_DELETE,
] as const

const ALL_COMPANY_ROLES = [
  P.COMPANY_ROLES_VIEW,
  P.COMPANY_ROLES_CREATE,
  P.COMPANY_ROLES_UPDATE,
  P.COMPANY_ROLES_DELETE,
] as const

const ALL_INVENTORY = [
  P.INVENTORY_VIEW,
  P.INVENTORY_CREATE,
  P.INVENTORY_UPDATE,
  P.INVENTORY_DELETE,
  P.INVENTORY_APPROVE,
] as const

const ALL_ITEMS = [
  P.ITEMS_VIEW,
  P.ITEMS_CREATE,
  P.ITEMS_UPDATE,
  P.ITEMS_DELETE,
  P.ITEMS_APPROVE,
] as const

const ALL_WAREHOUSES = [
  P.WAREHOUSES_VIEW,
  P.WAREHOUSES_CREATE,
  P.WAREHOUSES_UPDATE,
  P.WAREHOUSES_DELETE,
  P.WAREHOUSES_APPROVE,
] as const

const ALL_STOCK = [
  P.STOCK_VIEW,
  P.STOCK_ADJUST,
  P.STOCK_TRANSFER,
  P.STOCK_APPROVE,
] as const

const ALL_MOVEMENTS = [
  P.MOVEMENTS_VIEW,
  P.MOVEMENTS_CREATE,
  P.MOVEMENTS_UPDATE,
  P.MOVEMENTS_DELETE,
  P.MOVEMENTS_APPROVE,
] as const

const ALL_LOANS = [
  P.LOANS_VIEW,
  P.LOANS_CREATE,
  P.LOANS_UPDATE,
  P.LOANS_DELETE,
  P.LOANS_APPROVE,
] as const

const ALL_TRANSFERS = [
  P.TRANSFERS_VIEW,
  P.TRANSFERS_CREATE,
  P.TRANSFERS_UPDATE,
  P.TRANSFERS_DELETE,
  P.TRANSFERS_APPROVE,
] as const

const ALL_PURCHASE_ORDERS = [
  P.PURCHASES_ORDERS_VIEW,
  P.PURCHASES_ORDERS_CREATE,
  P.PURCHASES_ORDERS_UPDATE,
  P.PURCHASES_ORDERS_DELETE,
  P.PURCHASES_ORDERS_APPROVE,
  P.PURCHASES_ORDERS_RECEIVE,
] as const

const OPERATE_PURCHASE_ORDERS = [
  P.PURCHASES_ORDERS_VIEW,
  P.PURCHASES_ORDERS_CREATE,
  P.PURCHASES_ORDERS_UPDATE,
] as const

const VIEW_PURCHASE_ORDERS = [P.PURCHASES_ORDERS_VIEW] as const

const ALL_PURCHASE_SUPPLIERS = [
  P.PURCHASES_SUPPLIERS_VIEW,
  P.PURCHASES_SUPPLIERS_CREATE,
  P.PURCHASES_SUPPLIERS_UPDATE,
  P.PURCHASES_SUPPLIERS_DELETE,
] as const

const OPERATE_PURCHASE_SUPPLIERS = [
  P.PURCHASES_SUPPLIERS_VIEW,
  P.PURCHASES_SUPPLIERS_CREATE,
  P.PURCHASES_SUPPLIERS_UPDATE,
] as const

const VIEW_PURCHASE_SUPPLIERS = [P.PURCHASES_SUPPLIERS_VIEW] as const

const ALL_CUSTOMERS = [
  P.CUSTOMERS_VIEW,
  P.CUSTOMERS_CREATE,
  P.CUSTOMERS_UPDATE,
  P.CUSTOMERS_DELETE,
  P.CUSTOMERS_APPROVE,
] as const

const ALL_ORDERS = [
  P.ORDERS_VIEW,
  P.ORDERS_CREATE,
  P.ORDERS_UPDATE,
  P.ORDERS_DELETE,
  P.ORDERS_APPROVE,
] as const

const ALL_INVOICES = [
  P.INVOICES_VIEW,
  P.INVOICES_CREATE,
  P.INVOICES_UPDATE,
  P.INVOICES_DELETE,
  P.INVOICES_APPROVE,
] as const

const ALL_QUOTES = [
  P.QUOTES_VIEW,
  P.QUOTES_CREATE,
  P.QUOTES_UPDATE,
  P.QUOTES_DELETE,
  P.QUOTES_APPROVE,
] as const

const ALL_PAYMENTS = [
  P.PAYMENTS_VIEW,
  P.PAYMENTS_CREATE,
  P.PAYMENTS_UPDATE,
  P.PAYMENTS_DELETE,
  P.PAYMENTS_APPROVE,
] as const

const ALL_REPORTS = [
  P.REPORTS_VIEW,
  P.REPORTS_EXPORT,
  P.REPORTS_APPROVE,
] as const

const ALL_CRM = [
  P.CRM_CUSTOMERS_VIEW,
  P.CRM_CUSTOMERS_CREATE,
  P.CRM_CUSTOMERS_UPDATE,
  P.CRM_CUSTOMERS_DELETE,
  P.CRM_VEHICLES_VIEW,
  P.CRM_VEHICLES_CREATE,
  P.CRM_VEHICLES_UPDATE,
  P.CRM_VEHICLES_DELETE,
  P.CRM_LEADS_VIEW,
  P.CRM_LEADS_CREATE,
  P.CRM_LEADS_UPDATE,
  P.CRM_LEADS_DELETE,
  P.CRM_INTERACTIONS_VIEW,
  P.CRM_INTERACTIONS_CREATE,
  P.CRM_INTERACTIONS_UPDATE,
  P.CRM_INTERACTIONS_DELETE,
  P.CRM_ACTIVITIES_VIEW,
  P.CRM_ACTIVITIES_CREATE,
  P.CRM_ACTIVITIES_UPDATE,
  P.CRM_ACTIVITIES_DELETE,
  P.CRM_QUOTES_VIEW,
  P.CRM_QUOTES_CREATE,
  P.CRM_QUOTES_UPDATE,
  P.CRM_QUOTES_DELETE,
  P.CRM_CASES_VIEW,
  P.CRM_CASES_CREATE,
  P.CRM_CASES_UPDATE,
  P.CRM_CASES_DELETE,
  P.CRM_OPPORTUNITIES_VIEW,
  P.CRM_OPPORTUNITIES_CREATE,
  P.CRM_OPPORTUNITIES_UPDATE,
  P.CRM_OPPORTUNITIES_DELETE,
  P.CRM_CAMPAIGNS_VIEW,
  P.CRM_CAMPAIGNS_CREATE,
  P.CRM_CAMPAIGNS_UPDATE,
  P.CRM_CAMPAIGNS_DELETE,
  P.CRM_LOYALTY_VIEW,
  P.CRM_LOYALTY_CREATE,
  P.CRM_LOYALTY_UPDATE,
  P.CRM_LOYALTY_DELETE,
  P.CRM_AUTOMATIONS_VIEW,
] as const

const VIEW_CRM = [
  P.CRM_CUSTOMERS_VIEW,
  P.CRM_VEHICLES_VIEW,
  P.CRM_LEADS_VIEW,
  P.CRM_INTERACTIONS_VIEW,
  P.CRM_ACTIVITIES_VIEW,
  P.CRM_QUOTES_VIEW,
  P.CRM_CASES_VIEW,
  P.CRM_OPPORTUNITIES_VIEW,
  P.CRM_CAMPAIGNS_VIEW,
  P.CRM_LOYALTY_VIEW,
  P.CRM_AUTOMATIONS_VIEW,
] as const

const CRM_SERVICE_ADVISOR = [
  P.CRM_CUSTOMERS_VIEW,
  P.CRM_CUSTOMERS_CREATE,
  P.CRM_CUSTOMERS_UPDATE,
  P.CRM_VEHICLES_VIEW,
  P.CRM_VEHICLES_CREATE,
  P.CRM_VEHICLES_UPDATE,
  P.CRM_QUOTES_VIEW,
  P.CRM_QUOTES_CREATE,
  P.CRM_QUOTES_UPDATE,
  P.CRM_CASES_VIEW,
  P.CRM_CASES_CREATE,
  P.CRM_CASES_UPDATE,
  P.CRM_ACTIVITIES_VIEW,
  P.CRM_ACTIVITIES_CREATE,
  P.CRM_ACTIVITIES_UPDATE,
  P.CRM_INTERACTIONS_VIEW,
  P.CRM_INTERACTIONS_CREATE,
  P.CRM_INTERACTIONS_UPDATE,
] as const

const CRM_MARKETING = [
  P.CRM_CUSTOMERS_VIEW,
  P.CRM_LEADS_VIEW,
  P.CRM_LEADS_CREATE,
  P.CRM_LEADS_UPDATE,
  P.CRM_INTERACTIONS_VIEW,
  P.CRM_INTERACTIONS_CREATE,
  P.CRM_INTERACTIONS_UPDATE,
  P.CRM_ACTIVITIES_VIEW,
  P.CRM_ACTIVITIES_CREATE,
  P.CRM_ACTIVITIES_UPDATE,
  P.CRM_CAMPAIGNS_VIEW,
  P.CRM_CAMPAIGNS_CREATE,
  P.CRM_CAMPAIGNS_UPDATE,
  P.CRM_CAMPAIGNS_DELETE,
  P.CRM_LOYALTY_VIEW,
  P.CRM_LOYALTY_CREATE,
  P.CRM_LOYALTY_UPDATE,
  P.CRM_AUTOMATIONS_VIEW,
  P.CRM_AUTOMATIONS_RUN,
] as const

const CRM_DEALER = [
  P.CRM_CUSTOMERS_VIEW,
  P.CRM_CUSTOMERS_CREATE,
  P.CRM_CUSTOMERS_UPDATE,
  P.CRM_VEHICLES_VIEW,
  P.CRM_VEHICLES_CREATE,
  P.CRM_VEHICLES_UPDATE,
  P.CRM_LEADS_VIEW,
  P.CRM_LEADS_CREATE,
  P.CRM_LEADS_UPDATE,
  P.CRM_OPPORTUNITIES_VIEW,
  P.CRM_OPPORTUNITIES_CREATE,
  P.CRM_OPPORTUNITIES_UPDATE,
  P.CRM_QUOTES_VIEW,
  P.CRM_QUOTES_CREATE,
  P.CRM_QUOTES_UPDATE,
] as const

const ALL_WORKSHOP = [
  P.WORKSHOP_VIEW,
  P.WORKSHOP_CREATE,
  P.WORKSHOP_UPDATE,
  P.WORKSHOP_DELETE,
] as const

const OPERATE_WORKSHOP = [
  P.WORKSHOP_VIEW,
  P.WORKSHOP_CREATE,
  P.WORKSHOP_UPDATE,
] as const

const ALL_DEALER = [
  P.DEALER_VIEW,
  P.DEALER_CREATE,
  P.DEALER_UPDATE,
  P.DEALER_DELETE,
  P.DEALER_APPROVE,
] as const

const OPERATE_DEALER = [
  P.DEALER_VIEW,
  P.DEALER_CREATE,
  P.DEALER_UPDATE,
] as const

const ALL_EXCHANGE_RATES = [
  P.EXCHANGE_RATES_VIEW,
  P.EXCHANGE_RATES_CREATE,
  P.EXCHANGE_RATES_UPDATE,
  P.EXCHANGE_RATES_DELETE,
] as const

const ALL_FINANCE = [
  P.FINANCE_VIEW,
  P.FINANCE_BANK_ACCOUNT_VIEW,
  P.FINANCE_BANK_ACCOUNT_MANAGE,
  P.FINANCE_SUPPLIER_BILL_VIEW,
  P.FINANCE_SUPPLIER_BILL_MANAGE,
  P.FINANCE_SUPPLIER_PAYMENT_VIEW,
  P.FINANCE_SUPPLIER_PAYMENT_CREATE,
  P.FINANCE_SUPPLIER_PAYMENT_CANCEL,
  P.FINANCE_EXPENSE_VIEW,
  P.FINANCE_EXPENSE_MANAGE,
  P.FINANCE_RECURRING_RULE_MANAGE,
  P.FINANCE_CASH_FLOW_VIEW,
] as const

const VIEW_FINANCE = [
  P.FINANCE_VIEW,
  P.FINANCE_SUPPLIER_BILL_VIEW,
  P.FINANCE_SUPPLIER_PAYMENT_VIEW,
  P.FINANCE_EXPENSE_VIEW,
  P.FINANCE_CASH_FLOW_VIEW,
] as const

const NOTIFICATIONS_VIEW = [P.NOTIFICATIONS_VIEW] as const

const NOTIFICATIONS_MODULES_ALL = [
  P.INVENTORY_NOTIFICATIONS_VIEW,
  P.SALES_NOTIFICATIONS_VIEW,
  P.PURCHASES_NOTIFICATIONS_VIEW,
  P.WORKSHOP_NOTIFICATIONS_VIEW,
  P.CRM_NOTIFICATIONS_VIEW,
  P.DEALER_NOTIFICATIONS_VIEW,
  P.EXCHANGE_RATES_NOTIFICATIONS_VIEW,
  P.SYSTEM_NOTIFICATIONS_VIEW,
] as const

const NOTIFICATIONS_MODULES_NO_SYSTEM = [
  P.INVENTORY_NOTIFICATIONS_VIEW,
  P.SALES_NOTIFICATIONS_VIEW,
  P.PURCHASES_NOTIFICATIONS_VIEW,
  P.WORKSHOP_NOTIFICATIONS_VIEW,
  P.CRM_NOTIFICATIONS_VIEW,
  P.DEALER_NOTIFICATIONS_VIEW,
  P.EXCHANGE_RATES_NOTIFICATIONS_VIEW,
] as const

const NOTIFICATIONS_MODULES_VENDEDOR = [
  P.SALES_NOTIFICATIONS_VIEW,
  P.CRM_NOTIFICATIONS_VIEW,
  P.INVENTORY_NOTIFICATIONS_VIEW,
  P.DEALER_NOTIFICATIONS_VIEW,
] as const

const NOTIFICATIONS_MODULES_ALMACENISTA = [
  P.INVENTORY_NOTIFICATIONS_VIEW,
  P.PURCHASES_NOTIFICATIONS_VIEW,
] as const

const NOTIFICATIONS_MANAGE = [
  P.NOTIFICATIONS_VIEW,
  P.NOTIFICATIONS_MANAGE_POLICY,
  ...NOTIFICATIONS_MODULES_ALL,
] as const

export const DEFAULT_SYSTEM_PERMISSIONS_BY_ROLE: Record<string, string[]> = {
  OWNER: uniquePermissions(
    ALL_USERS,
    ALL_PLATFORM_USERS,
    ALL_COMPANIES,
    ALL_COMPANY_ROLES,
    ALL_INVENTORY,
    ALL_ITEMS,
    ALL_WAREHOUSES,
    ALL_STOCK,
    ALL_MOVEMENTS,
    ALL_LOANS,
    ALL_TRANSFERS,
    ALL_PURCHASE_ORDERS,
    ALL_PURCHASE_SUPPLIERS,
    ALL_CUSTOMERS,
    ALL_ORDERS,
    ALL_INVOICES,
    ALL_QUOTES,
    ALL_PAYMENTS,
    ALL_REPORTS,
    [P.AUDIT_VIEW],
    NOTIFICATIONS_MANAGE,
    ALL_CRM,
    [P.CRM_AUTOMATIONS_RUN],
    ALL_WORKSHOP,
    ALL_DEALER,
    ALL_EXCHANGE_RATES,
    ALL_FINANCE
  ),
  ADMIN: uniquePermissions(
    [P.USERS_VIEW, P.USERS_CREATE, P.USERS_UPDATE, P.USERS_APPROVE],
    ALL_PLATFORM_USERS,
    ALL_COMPANIES,
    ALL_COMPANY_ROLES,
    ALL_INVENTORY,
    ALL_ITEMS,
    ALL_WAREHOUSES,
    ALL_STOCK,
    ALL_MOVEMENTS,
    ALL_LOANS,
    ALL_TRANSFERS,
    ALL_PURCHASE_ORDERS,
    ALL_PURCHASE_SUPPLIERS,
    ALL_CUSTOMERS,
    ALL_ORDERS,
    ALL_INVOICES,
    ALL_QUOTES,
    ALL_PAYMENTS,
    ALL_REPORTS,
    [P.AUDIT_VIEW],
    NOTIFICATIONS_MANAGE,
    ALL_CRM,
    [P.CRM_AUTOMATIONS_RUN],
    ALL_WORKSHOP,
    ALL_DEALER,
    ALL_EXCHANGE_RATES,
    ALL_FINANCE
  ),
  GERENTE: uniquePermissions(
    [P.USERS_VIEW],
    ALL_INVENTORY,
    ALL_ITEMS,
    [
      P.WAREHOUSES_VIEW,
      P.WAREHOUSES_CREATE,
      P.WAREHOUSES_UPDATE,
      P.WAREHOUSES_APPROVE,
    ],
    ALL_STOCK,
    ALL_MOVEMENTS,
    ALL_LOANS,
    ALL_TRANSFERS,
    ALL_PURCHASE_ORDERS,
    ALL_PURCHASE_SUPPLIERS,
    ALL_CUSTOMERS,
    ALL_ORDERS,
    ALL_INVOICES,
    ALL_QUOTES,
    ALL_PAYMENTS,
    ALL_REPORTS,
    [P.AUDIT_VIEW],
    NOTIFICATIONS_MANAGE,
    ALL_CRM,
    [P.CRM_AUTOMATIONS_RUN],
    ALL_WORKSHOP,
    ALL_DEALER,
    ALL_EXCHANGE_RATES,
    ALL_FINANCE
  ),
  ALMACENISTA: uniquePermissions(
    [
      P.INVENTORY_VIEW,
      P.INVENTORY_CREATE,
      P.INVENTORY_UPDATE,
      P.INVENTORY_APPROVE,
      P.ITEMS_VIEW,
      P.ITEMS_CREATE,
      P.ITEMS_UPDATE,
      P.WAREHOUSES_VIEW,
      P.STOCK_VIEW,
      P.STOCK_ADJUST,
      P.STOCK_TRANSFER,
      P.MOVEMENTS_VIEW,
      P.MOVEMENTS_CREATE,
      P.MOVEMENTS_UPDATE,
      P.LOANS_VIEW,
      P.LOANS_CREATE,
      P.LOANS_UPDATE,
      P.TRANSFERS_VIEW,
      P.TRANSFERS_CREATE,
      P.TRANSFERS_UPDATE,
    ],
    VIEW_PURCHASE_ORDERS,
    VIEW_PURCHASE_SUPPLIERS,
    [P.PURCHASES_ORDERS_RECEIVE],
    OPERATE_WORKSHOP,
    [
      P.CRM_QUOTES_VIEW,
      P.CRM_QUOTES_CREATE,
      P.CRM_QUOTES_UPDATE,
      P.CRM_CASES_VIEW,
      P.CRM_CASES_CREATE,
      P.CRM_CASES_UPDATE,
      P.DEALER_VIEW,
      P.EXCHANGE_RATES_VIEW,
    ],
    NOTIFICATIONS_VIEW,
    NOTIFICATIONS_MODULES_ALMACENISTA
  ),
  VENDEDOR: uniquePermissions(
    [
      P.INVENTORY_VIEW,
      P.ITEMS_VIEW,
      P.WAREHOUSES_VIEW,
      P.STOCK_VIEW,
    ],
    ALL_CUSTOMERS,
    ALL_ORDERS,
    ALL_INVOICES,
    ALL_QUOTES,
    ALL_PAYMENTS,
    [P.REPORTS_VIEW],
    ALL_CRM,
    [P.WORKSHOP_VIEW],
    OPERATE_DEALER,
    [P.EXCHANGE_RATES_VIEW],
    NOTIFICATIONS_VIEW,
    NOTIFICATIONS_MODULES_VENDEDOR
  ),
  VIEWER: uniquePermissions(
    [
      P.USERS_VIEW,
      P.INVENTORY_VIEW,
      P.ITEMS_VIEW,
      P.WAREHOUSES_VIEW,
      P.STOCK_VIEW,
      P.MOVEMENTS_VIEW,
      P.LOANS_VIEW,
      P.TRANSFERS_VIEW,
      P.CUSTOMERS_VIEW,
      P.ORDERS_VIEW,
      P.INVOICES_VIEW,
      P.QUOTES_VIEW,
      P.PAYMENTS_VIEW,
      P.REPORTS_VIEW,
      P.WORKSHOP_VIEW,
      P.DEALER_VIEW,
      P.EXCHANGE_RATES_VIEW,
    ],
    VIEW_PURCHASE_ORDERS,
    VIEW_PURCHASE_SUPPLIERS,
    VIEW_CRM,
    VIEW_FINANCE,
    NOTIFICATIONS_VIEW,
    NOTIFICATIONS_MODULES_NO_SYSTEM
  ),
  COMPRADOR: uniquePermissions(
    OPERATE_PURCHASE_SUPPLIERS,
    OPERATE_PURCHASE_ORDERS,
    [
      P.INVENTORY_VIEW,
      P.ITEMS_VIEW,
      P.WAREHOUSES_VIEW,
      P.STOCK_VIEW,
      P.REPORTS_VIEW,
      P.EXCHANGE_RATES_VIEW,
    ],
    NOTIFICATIONS_VIEW,
    [P.PURCHASES_NOTIFICATIONS_VIEW]
  ),
  JEFE_COMPRAS: uniquePermissions(
    OPERATE_PURCHASE_SUPPLIERS,
    [P.PURCHASES_SUPPLIERS_DELETE],
    OPERATE_PURCHASE_ORDERS,
    [
      P.PURCHASES_ORDERS_DELETE,
      P.PURCHASES_ORDERS_APPROVE,
      P.PURCHASES_ORDERS_RECEIVE,
      P.INVENTORY_VIEW,
      P.ITEMS_VIEW,
      P.WAREHOUSES_VIEW,
      P.STOCK_VIEW,
      P.REPORTS_VIEW,
      P.REPORTS_EXPORT,
      P.EXCHANGE_RATES_VIEW,
    ],
    NOTIFICATIONS_VIEW,
    [P.PURCHASES_NOTIFICATIONS_VIEW]
  ),
  ADMINISTRACION: uniquePermissions(
    ALL_FINANCE,
    VIEW_PURCHASE_ORDERS,
    VIEW_PURCHASE_SUPPLIERS,
    [P.REPORTS_VIEW, P.REPORTS_EXPORT, P.AUDIT_VIEW],
    ALL_EXCHANGE_RATES,
    NOTIFICATIONS_VIEW,
    [P.EXCHANGE_RATES_NOTIFICATIONS_VIEW]
  ),
  CAJERO: uniquePermissions(
    [
      P.PAYMENTS_VIEW,
      P.PAYMENTS_CREATE,
      P.PAYMENTS_UPDATE,
      P.INVOICES_VIEW,
      P.ORDERS_VIEW,
      P.CUSTOMERS_VIEW,
      P.FINANCE_VIEW,
      P.FINANCE_BANK_ACCOUNT_VIEW,
      P.FINANCE_SUPPLIER_PAYMENT_VIEW,
      P.FINANCE_SUPPLIER_PAYMENT_CREATE,
      P.REPORTS_VIEW,
    ],
    VIEW_PURCHASE_SUPPLIERS,
    NOTIFICATIONS_VIEW,
    [P.SALES_NOTIFICATIONS_VIEW]
  ),
  CONTADOR: uniquePermissions(
    [
      P.FINANCE_VIEW,
      P.FINANCE_BANK_ACCOUNT_VIEW,
      P.FINANCE_SUPPLIER_BILL_VIEW,
      P.FINANCE_SUPPLIER_BILL_MANAGE,
      P.FINANCE_SUPPLIER_PAYMENT_VIEW,
      P.FINANCE_SUPPLIER_PAYMENT_CANCEL,
      P.FINANCE_EXPENSE_VIEW,
      P.FINANCE_EXPENSE_MANAGE,
      P.FINANCE_CASH_FLOW_VIEW,
      P.REPORTS_VIEW,
      P.REPORTS_EXPORT,
      P.EXCHANGE_RATES_VIEW,
    ],
    VIEW_PURCHASE_ORDERS,
    VIEW_PURCHASE_SUPPLIERS,
    NOTIFICATIONS_VIEW,
    [P.EXCHANGE_RATES_NOTIFICATIONS_VIEW]
  ),
  TECNICO_TALLER: uniquePermissions(
    OPERATE_WORKSHOP,
    [P.CRM_CUSTOMERS_VIEW, P.CRM_VEHICLES_VIEW],
    [P.INVENTORY_VIEW, P.ITEMS_VIEW, P.WAREHOUSES_VIEW, P.STOCK_VIEW],
    NOTIFICATIONS_VIEW,
    [P.WORKSHOP_NOTIFICATIONS_VIEW]
  ),
  JEFE_TALLER: uniquePermissions(
    ALL_WORKSHOP,
    [
      P.REPORTS_VIEW,
      P.REPORTS_EXPORT,
      P.INVENTORY_VIEW,
      P.ITEMS_VIEW,
      P.WAREHOUSES_VIEW,
      P.STOCK_VIEW,
      P.STOCK_APPROVE,
    ],
    NOTIFICATIONS_VIEW,
    [P.WORKSHOP_NOTIFICATIONS_VIEW]
  ),
  ASESOR_SERVICIO: uniquePermissions(
    OPERATE_WORKSHOP,
    CRM_SERVICE_ADVISOR,
    [P.REPORTS_VIEW],
    NOTIFICATIONS_VIEW,
    [P.WORKSHOP_NOTIFICATIONS_VIEW, P.CRM_NOTIFICATIONS_VIEW]
  ),
  CRM_MARKETING: uniquePermissions(
    CRM_MARKETING,
    [P.REPORTS_VIEW, P.REPORTS_EXPORT],
    NOTIFICATIONS_VIEW,
    [P.CRM_NOTIFICATIONS_VIEW]
  ),
  CONCESIONARIO: uniquePermissions(
    OPERATE_DEALER,
    CRM_DEALER,
    [P.REPORTS_VIEW],
    NOTIFICATIONS_VIEW,
    [P.DEALER_NOTIFICATIONS_VIEW, P.CRM_NOTIFICATIONS_VIEW]
  ),
}

export const DEFAULT_SYSTEM_ROLE_NAMES = Object.keys(
  DEFAULT_SYSTEM_PERMISSIONS_BY_ROLE
)
