import { PERMISSIONS } from '../../shared/constants/permissions.js'

export type NotificationPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL'
export type NotificationSeverity = 'INFO' | 'WARNING' | 'ERROR' | 'SUCCESS'
export type NotificationChannel = 'IN_APP'

export interface NotificationCatalogItem {
  eventCode: string
  module: string
  title: string
  description: string
  defaultEnabled: boolean
  defaultMandatory: boolean
  defaultPriority: NotificationPriority
  defaultSeverity: NotificationSeverity
  defaultDedupWindowSec: number
  requiredPermissionsAny: string[]
  channels: NotificationChannel[]
}

interface NotificationCatalogInternalItem extends NotificationCatalogItem {
  aliases?: string[]
  active?: boolean
  visibleInCatalog?: boolean
}

const MODULE_NOTIFICATION_PERMISSIONS: Record<string, string> = {
  inventory: PERMISSIONS.INVENTORY_NOTIFICATIONS_VIEW,
  sales: PERMISSIONS.SALES_NOTIFICATIONS_VIEW,
  purchases: PERMISSIONS.PURCHASES_NOTIFICATIONS_VIEW,
  workshop: PERMISSIONS.WORKSHOP_NOTIFICATIONS_VIEW,
  crm: PERMISSIONS.CRM_NOTIFICATIONS_VIEW,
  dealer: PERMISSIONS.DEALER_NOTIFICATIONS_VIEW,
  exchange_rates: PERMISSIONS.EXCHANGE_RATES_NOTIFICATIONS_VIEW,
  system: PERMISSIONS.SYSTEM_NOTIFICATIONS_VIEW,
}

const CATALOG_INTERNAL: NotificationCatalogInternalItem[] = [
  {
    eventCode: 'inventory.exit_note.created',
    module: 'inventory',
    title: 'Nota de salida creada',
    description: 'Se creó una nueva nota de salida',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.stock.low',
    module: 'inventory',
    title: 'Stock bajo',
    description: 'Un artículo quedó en o por debajo del umbral mínimo',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 300,
    requiredPermissionsAny: ['stock.view'],
    channels: ['IN_APP'],
    aliases: ['stock.low', 'stock.lowAlert'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.stock.critical',
    module: 'inventory',
    title: 'Stock crítico',
    description: 'Un artículo alcanzó un nivel crítico de inventario',
    defaultEnabled: true,
    defaultMandatory: true,
    defaultPriority: 'CRITICAL',
    defaultSeverity: 'ERROR',
    defaultDedupWindowSec: 300,
    requiredPermissionsAny: ['stock.view'],
    channels: ['IN_APP'],
    aliases: ['stock.criticalAlert'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.entry_note.created',
    module: 'inventory',
    title: 'Nota de entrada creada',
    description: 'Se creó una nueva nota de entrada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.transfer.created',
    module: 'inventory',
    title: 'Transferencia creada',
    description: 'Se creó una nueva transferencia entre almacenes',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['transfers.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.transfer.approved',
    module: 'inventory',
    title: 'Transferencia aprobada',
    description: 'Una transferencia fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['transfers.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.transfer.in_transit',
    module: 'inventory',
    title: 'Transferencia en tránsito',
    description: 'Una transferencia fue despachada y está en tránsito',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['transfers.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.transfer.received',
    module: 'inventory',
    title: 'Transferencia recibida',
    description: 'Una transferencia fue recibida en almacén destino',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['transfers.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.transfer.cancelled',
    module: 'inventory',
    title: 'Transferencia cancelada',
    description: 'Una transferencia fue cancelada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['transfers.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.adjustment.created',
    module: 'inventory',
    title: 'Ajuste creado',
    description: 'Se creó un nuevo ajuste de inventario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.adjustment.approved',
    module: 'inventory',
    title: 'Ajuste aprobado',
    description: 'Un ajuste de inventario fue aprobado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.adjustment.applied',
    module: 'inventory',
    title: 'Ajuste aplicado',
    description: 'Un ajuste de inventario fue aplicado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.adjustment.rejected',
    module: 'inventory',
    title: 'Ajuste rechazado',
    description: 'Un ajuste de inventario fue rechazado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.adjustment.cancelled',
    module: 'inventory',
    title: 'Ajuste cancelado',
    description: 'Un ajuste de inventario fue cancelado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reservation.created',
    module: 'inventory',
    title: 'Reserva creada',
    description: 'Se creó una nueva reserva de inventario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reservation.pending_pickup',
    module: 'inventory',
    title: 'Reserva pendiente por retiro',
    description: 'Una reserva cambió a pendiente por retiro',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reservation.consumed',
    module: 'inventory',
    title: 'Reserva consumida',
    description: 'Una reserva fue consumida y el stock fue entregado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reservation.released',
    module: 'inventory',
    title: 'Reserva liberada',
    description: 'Una reserva fue liberada y el stock volvió a disponible',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reservation.deleted',
    module: 'inventory',
    title: 'Reserva eliminada',
    description: 'Una reserva activa fue eliminada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.loan.created',
    module: 'inventory',
    title: 'Préstamo creado',
    description: 'Se creó un nuevo préstamo de inventario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['loans.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.loan.approved',
    module: 'inventory',
    title: 'Préstamo aprobado',
    description: 'Un préstamo de inventario fue aprobado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['loans.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.loan.active',
    module: 'inventory',
    title: 'Préstamo activo',
    description: 'Un préstamo de inventario fue activado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['loans.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.loan.returned',
    module: 'inventory',
    title: 'Préstamo retornado',
    description: 'Un préstamo de inventario fue retornado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['loans.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.loan.overdue',
    module: 'inventory',
    title: 'Préstamo vencido',
    description: 'Un préstamo de inventario está vencido',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 300,
    requiredPermissionsAny: ['loans.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.cycle_count.created',
    module: 'inventory',
    title: 'Conteo cíclico creado',
    description: 'Se creó un nuevo conteo cíclico',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.cycle_count.completed',
    module: 'inventory',
    title: 'Conteo cíclico completado',
    description: 'Un conteo cíclico fue completado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.cycle_count.approved',
    module: 'inventory',
    title: 'Conteo cíclico aprobado',
    description: 'Un conteo cíclico fue aprobado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.cycle_count.applied',
    module: 'inventory',
    title: 'Conteo cíclico aplicado',
    description: 'Un conteo cíclico fue aplicado al stock',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.cycle_count.rejected',
    module: 'inventory',
    title: 'Conteo cíclico rechazado',
    description: 'Un conteo cíclico fue rechazado o cancelado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reconciliation.created',
    module: 'inventory',
    title: 'Reconciliación creada',
    description: 'Se creó una nueva reconciliación de inventario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reconciliation.approved',
    module: 'inventory',
    title: 'Reconciliación aprobada',
    description: 'Una reconciliación de inventario fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reconciliation.applied',
    module: 'inventory',
    title: 'Reconciliación aplicada',
    description: 'Una reconciliación de inventario fue aplicada al stock',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.reconciliation.rejected',
    module: 'inventory',
    title: 'Reconciliación rechazada',
    description: 'Una reconciliación de inventario fue rechazada o cancelada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.return.created',
    module: 'inventory',
    title: 'Devolución creada',
    description: 'Se creó una nueva devolución',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.return.approved',
    module: 'inventory',
    title: 'Devolución aprobada',
    description: 'Una devolución fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.return.processed',
    module: 'inventory',
    title: 'Devolución procesada',
    description: 'Una devolución fue procesada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.return.rejected',
    module: 'inventory',
    title: 'Devolución rechazada',
    description: 'Una devolución fue rechazada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.serial_number.created',
    module: 'inventory',
    title: 'Serial creado',
    description: 'Se registró un nuevo serial de inventario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'LOW',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.serial_number.status_changed',
    module: 'inventory',
    title: 'Estado de serial actualizado',
    description: 'Un serial de inventario cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'inventory.serial_number.assigned_location',
    module: 'inventory',
    title: 'Serial asignado a ubicación',
    description: 'Un serial de inventario fue asignado a un almacén',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'LOW',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.order.created',
    module: 'sales',
    title: 'Orden de venta creada',
    description: 'Se creó una nueva orden de venta',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['orders.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.order.approved',
    module: 'sales',
    title: 'Orden aprobada',
    description: 'Una orden de venta fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['orders.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.order.cancelled',
    module: 'sales',
    title: 'Orden cancelada',
    description: 'Una orden de venta fue cancelada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['orders.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.payment.completed',
    module: 'sales',
    title: 'Pago completado',
    description: 'Se completó un pago de una pre-factura',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['payments.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.pre_invoice.created',
    module: 'sales',
    title: 'Pre-factura creada',
    description: 'Se generó una nueva pre-factura',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['orders.view', 'invoices.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.pre_invoice.cancelled',
    module: 'sales',
    title: 'Pre-factura cancelada',
    description: 'Una pre-factura fue cancelada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['orders.view', 'invoices.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.invoice.issued',
    module: 'sales',
    title: 'Factura emitida',
    description: 'Se emitió una factura',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['invoices.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'sales.invoice.cancelled',
    module: 'sales',
    title: 'Factura anulada',
    description: 'Una factura fue anulada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['invoices.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.quote.created',
    module: 'dealer',
    title: 'Cotización de concesionario creada',
    description: 'Se creó una nueva cotización en concesionario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    aliases: ['sales.quote.created'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.quote.approved',
    module: 'dealer',
    title: 'Cotización de concesionario aprobada',
    description: 'Una cotización de concesionario fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    aliases: ['sales.quote.approved'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.quote.rejected',
    module: 'dealer',
    title: 'Cotización de concesionario rechazada',
    description: 'Una cotización de concesionario fue rechazada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    aliases: ['sales.quote.rejected'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.quote.converted',
    module: 'dealer',
    title: 'Cotización de concesionario convertida',
    description: 'Una cotización de concesionario fue convertida y fiscalizada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    aliases: ['sales.quote.converted'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.reservation.created',
    module: 'dealer',
    title: 'Reserva de concesionario creada',
    description: 'Se creó una nueva reserva de unidad en concesionario',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.reservation.status_changed',
    module: 'dealer',
    title: 'Estado de reserva actualizado',
    description: 'Una reserva de concesionario cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.test_drive.created',
    module: 'dealer',
    title: 'Prueba de manejo creada',
    description: 'Se creó una nueva prueba de manejo',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.test_drive.status_changed',
    module: 'dealer',
    title: 'Estado de prueba de manejo actualizado',
    description: 'Una prueba de manejo cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.financing.created',
    module: 'dealer',
    title: 'Financiamiento creado',
    description: 'Se creó una nueva solicitud de financiamiento',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.financing.status_changed',
    module: 'dealer',
    title: 'Estado de financiamiento actualizado',
    description: 'Una solicitud de financiamiento cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.delivery.created',
    module: 'dealer',
    title: 'Entrega de concesionario creada',
    description: 'Se creó una nueva entrega de vehículo',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.delivery.status_changed',
    module: 'dealer',
    title: 'Estado de entrega actualizado',
    description: 'Una entrega de concesionario cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.trade_in.created',
    module: 'dealer',
    title: 'Retoma creada',
    description: 'Se creó una nueva retoma de vehículo',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'dealer.trade_in.status_changed',
    module: 'dealer',
    title: 'Estado de retoma actualizado',
    description: 'Una retoma de concesionario cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['dealer.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'purchases.purchase_order.created',
    module: 'purchases',
    title: 'Orden de compra creada',
    description: 'Se creó una nueva orden de compra',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'purchases.purchase_order.approved',
    module: 'purchases',
    title: 'Orden de compra aprobada',
    description: 'Una orden de compra fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'purchases.purchase_order.cancelled',
    module: 'purchases',
    title: 'Orden de compra cancelada',
    description: 'Una orden de compra fue cancelada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 180,
    requiredPermissionsAny: ['inventory.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order.created',
    module: 'workshop',
    title: 'Orden de taller creada',
    description: 'Se creó una nueva orden de taller',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order.status_changed',
    module: 'workshop',
    title: 'Estado de orden de taller actualizado',
    description: 'Una orden de taller cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order.ready',
    module: 'workshop',
    title: 'Orden de taller lista',
    description: 'Una orden de taller quedó lista para entrega',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order.delivered',
    module: 'workshop',
    title: 'Orden de taller entregada',
    description: 'Se entregó una orden de taller',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.appointment.created',
    module: 'workshop',
    title: 'Cita de taller creada',
    description: 'Se creó una nueva cita de taller',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.appointment.rescheduled',
    module: 'workshop',
    title: 'Cita reprogramada',
    description: 'Una cita de taller fue reprogramada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.appointment.cancelled',
    module: 'workshop',
    title: 'Cita cancelada',
    description: 'Una cita de taller fue cancelada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.appointment.no_show',
    module: 'workshop',
    title: 'Cliente no asistió',
    description: 'La cita quedó en estado no_show',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quotation.created',
    module: 'workshop',
    title: 'Cotización de taller creada',
    description: 'Se creó una cotización de taller',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quotation.approved',
    module: 'workshop',
    title: 'Cotización de taller aprobada',
    description: 'Una cotización de taller fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quotation.rejected',
    module: 'workshop',
    title: 'Cotización de taller rechazada',
    description: 'Una cotización de taller fue rechazada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quotation.converted',
    module: 'workshop',
    title: 'Cotización convertida',
    description: 'Una cotización de taller fue convertida a orden',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.reception.created',
    module: 'workshop',
    title: 'Recepción creada',
    description: 'Se registró una nueva recepción de vehículo',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.reception.status_changed',
    module: 'workshop',
    title: 'Estado de recepción actualizado',
    description: 'Una recepción de vehículo cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.delivery.created',
    module: 'workshop',
    title: 'Entrega registrada',
    description: 'Se registró la entrega de una orden de taller',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order_material.created',
    module: 'workshop',
    title: 'Material de OT creado',
    description: 'Se agregó un material a una orden de taller',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order_material.status_changed',
    module: 'workshop',
    title: 'Estado de material OT actualizado',
    description: 'Un material de orden de taller cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.service_order_material.client_approval_updated',
    module: 'workshop',
    title: 'Aprobación de material actualizada',
    description: 'La aprobación del cliente sobre un material fue actualizada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quality_check.created',
    module: 'workshop',
    title: 'Control de calidad creado',
    description: 'Se inició un nuevo control de calidad',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quality_check.passed',
    module: 'workshop',
    title: 'Control de calidad aprobado',
    description: 'Un control de calidad fue aprobado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.quality_check.failed',
    module: 'workshop',
    title: 'Control de calidad rechazado',
    description: 'Un control de calidad fue rechazado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.garita.created',
    module: 'workshop',
    title: 'Registro de garita creado',
    description: 'Se registró un nuevo evento de garita',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'workshop.garita.status_changed',
    module: 'workshop',
    title: 'Estado de garita actualizado',
    description: 'Un registro de garita cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['workshop.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.lead.created',
    module: 'crm',
    title: 'Lead creado',
    description: 'Se creó un nuevo lead',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.leads.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.lead.status_changed',
    module: 'crm',
    title: 'Estado de lead actualizado',
    description: 'Un lead cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['crm.leads.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.lead.converted',
    module: 'crm',
    title: 'Lead convertido',
    description: 'Un lead fue convertido a oportunidad',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.leads.view', 'crm.opportunities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.opportunity.created',
    module: 'crm',
    title: 'Oportunidad creada',
    description: 'Se creó una nueva oportunidad',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.opportunities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.opportunity.stage_changed',
    module: 'crm',
    title: 'Etapa de oportunidad actualizada',
    description: 'Una oportunidad cambió de etapa',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['crm.opportunities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.opportunity.won',
    module: 'crm',
    title: 'Oportunidad ganada',
    description: 'Una oportunidad se cerró como ganada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.opportunities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.opportunity.lost',
    module: 'crm',
    title: 'Oportunidad perdida',
    description: 'Una oportunidad se cerró como perdida',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.opportunities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.activity.created',
    module: 'crm',
    title: 'Actividad creada',
    description: 'Se creó una nueva actividad CRM',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'LOW',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 60,
    requiredPermissionsAny: ['crm.activities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.activity.completed',
    module: 'crm',
    title: 'Actividad completada',
    description: 'Una actividad CRM fue completada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'LOW',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 60,
    requiredPermissionsAny: ['crm.activities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.activity.overdue',
    module: 'crm',
    title: 'Actividad vencida',
    description: 'Una actividad CRM está vencida',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 600,
    requiredPermissionsAny: ['crm.activities.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.case.opened',
    module: 'crm',
    title: 'Caso abierto',
    description: 'Se abrió un nuevo caso CRM',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.cases.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.case.escalated',
    module: 'crm',
    title: 'Caso escalado',
    description: 'Un caso CRM fue escalado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.cases.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.case.closed',
    module: 'crm',
    title: 'Caso cerrado',
    description: 'Un caso CRM fue cerrado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.cases.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.quote.created',
    module: 'crm',
    title: 'Cotización CRM creada',
    description: 'Se creó una nueva cotización CRM',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.quotes.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.quote.status_changed',
    module: 'crm',
    title: 'Estado de cotización CRM actualizado',
    description: 'Una cotización CRM cambió de estado',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 90,
    requiredPermissionsAny: ['crm.quotes.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.quote.approved',
    module: 'crm',
    title: 'Cotización CRM aprobada',
    description: 'Una cotización CRM fue aprobada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'SUCCESS',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.quotes.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.quote.rejected',
    module: 'crm',
    title: 'Cotización CRM rechazada',
    description: 'Una cotización CRM fue rechazada',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.quotes.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'crm.quote.revised',
    module: 'crm',
    title: 'Cotización CRM revisada',
    description: 'Se creó una nueva versión de cotización CRM',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'MEDIUM',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: ['crm.quotes.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'exchange_rates.bcv.fetched',
    module: 'exchange_rates',
    title: 'Tasa BCV actualizada',
    description: 'Se actualizaron las tasas BCV',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'LOW',
    defaultSeverity: 'INFO',
    defaultDedupWindowSec: 600,
    requiredPermissionsAny: ['exchange_rates.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'exchange_rates.bcv.fetch_failed',
    module: 'exchange_rates',
    title: 'Error actualizando tasa BCV',
    description: 'Falló el proceso de actualización BCV',
    defaultEnabled: true,
    defaultMandatory: true,
    defaultPriority: 'CRITICAL',
    defaultSeverity: 'ERROR',
    defaultDedupWindowSec: 600,
    requiredPermissionsAny: ['exchange_rates.view'],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'system.warning',
    module: 'system',
    title: 'Advertencia de sistema',
    description: 'Evento de advertencia del sistema',
    defaultEnabled: true,
    defaultMandatory: false,
    defaultPriority: 'HIGH',
    defaultSeverity: 'WARNING',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: [],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
  {
    eventCode: 'system.error',
    module: 'system',
    title: 'Error de sistema',
    description: 'Evento crítico de error del sistema',
    defaultEnabled: true,
    defaultMandatory: true,
    defaultPriority: 'CRITICAL',
    defaultSeverity: 'ERROR',
    defaultDedupWindowSec: 120,
    requiredPermissionsAny: [],
    channels: ['IN_APP'],
    active: true,
    visibleInCatalog: true,
  },
]

const CATALOG = CATALOG_INTERNAL.filter((item) => item.active !== false)
const CATALOG_MAP = new Map(CATALOG.map((item) => [item.eventCode, item]))
const ALIAS_TO_CANONICAL = new Map<string, string>()

for (const item of CATALOG) {
  for (const alias of item.aliases ?? []) {
    ALIAS_TO_CANONICAL.set(alias, item.eventCode)
  }
}

const toPublicItem = (item: NotificationCatalogInternalItem): NotificationCatalogItem => ({
  eventCode: item.eventCode,
  module: item.module,
  title: item.title,
  description: item.description,
  defaultEnabled: item.defaultEnabled,
  defaultMandatory: item.defaultMandatory,
  defaultPriority: item.defaultPriority,
  defaultSeverity: item.defaultSeverity,
  defaultDedupWindowSec: item.defaultDedupWindowSec,
  requiredPermissionsAny: item.requiredPermissionsAny,
  channels: item.channels,
})

export const resolveNotificationEventCode = (eventCode: string): string => {
  if (!eventCode || typeof eventCode !== 'string') return eventCode
  const normalized = eventCode.trim()
  return ALIAS_TO_CANONICAL.get(normalized) ?? normalized
}

export const getNotificationEventAliases = (eventCode: string): string[] => {
  const canonical = resolveNotificationEventCode(eventCode)
  const item = CATALOG_MAP.get(canonical)
  return item?.aliases ?? []
}

export const getNotificationCatalog = (options?: {
  includeHidden?: boolean
}): NotificationCatalogItem[] => {
  const includeHidden = Boolean(options?.includeHidden)

  return CATALOG.filter((item) => {
    if (includeHidden) return true
    return item.visibleInCatalog !== false
  }).map(toPublicItem)
}

export const getNotificationCatalogItem = (
  eventCode: string
): NotificationCatalogItem | undefined => {
  const canonical = resolveNotificationEventCode(eventCode)
  const item = CATALOG_MAP.get(canonical)
  return item ? toPublicItem(item) : undefined
}

export const resolveModuleFromEventCode = (eventCode: string): string => {
  const fromCatalog = getNotificationCatalogItem(eventCode)
  if (fromCatalog) return fromCatalog.module

  const [prefix] = resolveNotificationEventCode(eventCode).split('.')
  if (prefix) return prefix
  return 'system'
}

export const getModuleNotificationPermission = (
  module: string
): string | undefined => {
  if (!module || typeof module !== 'string') return undefined
  return MODULE_NOTIFICATION_PERMISSIONS[module.trim()]
}

export const isHardLockedNotification = (
  severity?: string,
  priority?: string
): boolean => {
  const normalizedSeverity = (severity ?? '').trim().toUpperCase()
  const normalizedPriority = (priority ?? '').trim().toUpperCase()
  return normalizedSeverity === 'ERROR' || normalizedPriority === 'CRITICAL'
}

export const isNotificationCatalogItemHardLocked = (
  item: NotificationCatalogItem
): boolean =>
  isHardLockedNotification(item.defaultSeverity, item.defaultPriority)

export const canAccessNotificationCatalogItem = (
  item: NotificationCatalogItem,
  effectivePermissions: Set<string>
): boolean => {
  if (!effectivePermissions.has(PERMISSIONS.NOTIFICATIONS_VIEW)) return false

  const modulePermission = getModuleNotificationPermission(item.module)
  if (modulePermission && !effectivePermissions.has(modulePermission)) {
    return false
  }

  if (
    item.requiredPermissionsAny.length > 0 &&
    !item.requiredPermissionsAny.some((perm) => effectivePermissions.has(perm))
  ) {
    return false
  }

  return true
}

export const getVisibleNotificationCatalogByPermissions = (
  effectivePermissions: Set<string>,
  options?: { includeHidden?: boolean }
): NotificationCatalogItem[] => {
  return getNotificationCatalog(options).filter((item) =>
    canAccessNotificationCatalogItem(item, effectivePermissions)
  )
}

export const isNotificationEventVisible = (
  eventCode: string,
  module: string | undefined,
  effectivePermissions: Set<string>
): boolean => {
  const catalogItem = getNotificationCatalogItem(eventCode)

  if (catalogItem) {
    return canAccessNotificationCatalogItem(catalogItem, effectivePermissions)
  }

  if (!effectivePermissions.has(PERMISSIONS.NOTIFICATIONS_VIEW)) return false

  const resolvedModule =
    (module && module.trim()) || resolveModuleFromEventCode(eventCode)
  const modulePermission = getModuleNotificationPermission(resolvedModule)

  if (modulePermission && !effectivePermissions.has(modulePermission)) {
    return false
  }

  return true
}
