// libs/interfaces/workshop/index.ts
export * from './shared.interface'
export * from './serviceType.interface'
export * from './workshopBay.interface'
export * from './workshopOperation.interface'
export * from './serviceOrder.interface'
export * from './appointment.interface'
export * from './reception.interface'
export * from './laborTime.interface'
export * from './qualityCheck.interface'
export * from './warranty.interface'
