-- CreateTable
CREATE TABLE "Empresa" (
    "id_empresa" TEXT NOT NULL,
    "nombre" TEXT NOT NULL,
    "direccion" TEXT,
    "telefonos" TEXT,
    "fax" TEXT,
    "numerorif" TEXT,
    "numeronit" TEXT,
    "website" TEXT,
    "email" TEXT,
    "contacto" TEXT,
    "predeter" BOOLEAN NOT NULL DEFAULT false,
    "soporte1" TEXT,
    "soporte2" TEXT,
    "soporte3" TEXT,
    "data_usaweb" BOOLEAN NOT NULL DEFAULT false,
    "data_servidor" TEXT,
    "data_usuario" TEXT,
    "data_password" TEXT,
    "data_port" TEXT,
    "licencia" TEXT,
    "historizada" BOOLEAN NOT NULL DEFAULT false,
    "masinfo" TEXT,
    "usa_prefijo" BOOLEAN NOT NULL DEFAULT false,
    "name_prefijo" TEXT,
    "dprefijobd" TEXT,
    "dprefijosrv" TEXT,
    "dprefijousr" TEXT,
    "eliminado" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Empresa_pkey" PRIMARY KEY ("id_empresa")
);
